name: Tests
on: [push]
jobs:
  test-codebase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}
      - run: go test ./chainlets -count=1
      - name: Run coverage
        run: go test -race -coverprofile=coverage.txt -covermode=atomic ./chainlets
      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}